name: CollegeMC-Core
version: '${project.version}'
main: net.collegemc.mc.core.CollegeCore
api-version: 1.19
authors: [ Gestankbratwurst ]
description: Core plugin for CollegeMC functionality
depend:
  - CollegeMC-Libs