name: CollegeMC-Lobby
version: '1.0.0-SNAPSHOT'
main: net.collegemc.mc.lobby.CollegeLobby
api-version: 1.19
authors: [ Gestankbratwurst ]
description: Lobby plugin for CollegeMC
depend:
  - CollegeMC-Libs
  - CollegeMC-Core